name: DevSecOps Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  sast-bandit:
    name: SAST with Bandit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Bandit
        # We add '|| true' so the step doesn't fail the job immediately
        # The job will still fail if trivy finds issues later, or we can add a final check
        run: |
          pip install bandit
          bandit -r . -f json -o bandit-report.json || true
      - name: Upload Bandit report
        # This step will now always run
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.json
      - name: Check for Bandit findings
        # This step fails the job if the report contains issues
        run: |
          if [ -s bandit-report.json ] && [ "$(jq '.results | length' bandit-report.json)" -gt 0 ]; then
            echo "Bandit found vulnerabilities. Failing the build."
            exit 1
          else
            echo "No Bandit vulnerabilities found."
          fi
  sca-trivy:
    name: SCA with Trivy
    runs-on: ubuntu-latest
    needs: sast-bandit
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          # Make trivy exit with 0 so the next step can run
          exit-code: '0'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
      - name: Fail build on critical/high vulnerabilities
        # This step fails the job if trivy found issues
        run: |
          # The trivy action writes the number of vulnerabilities to a file
          # We check if that number is greater than 0
          if [ -f "trivy-results.sarif" ] && [ "$(jq '.runs[0].results | length' trivy-results.sarif)" -gt 0 ]; then
            echo "Trivy found critical or high severity vulnerabilities. Failing the build."
            exit 1
          else
            echo "No critical or high severity vulnerabilities found by Trivy."
          fi